FROM node:22 AS build
WORKDIR /app

# Copie uniquement package.json pour optimiser le cache
COPY package.json package-lock.json ./

RUN npm install

# Copie tout le projet
COPY . .

# Build frontend JHipster
RUN npm run webapp:prod

# Étape Nginx
FROM nginx:alpine

# JHipster met les fichiers construits ici :
COPY --from=build /app/target/classes/static/ /usr/share/nginx/html

EXPOSE 80
